[meta]
save_dir = "exp"
description = "Train a model using Generative Adversarial Networks (GANs)"
seed = 20220815

[trainer]
path = "trainer.Trainer"
[trainer.args]
debug = false
max_steps = 0
max_epochs = 200
max_grad_norm = 10
save_max_score = true
save_ckpt_interval = 5
max_patience = 200
plot_norm = true
validation_interval = 5
max_num_checkpoints = 20
scheduler_name = "constant_schedule_with_warmup"
warmup_steps = 0
warmup_ratio = 0.00
gradient_accumulation_steps = 1

[loss_function]
path = "torch.nn.MSELoss"
[loss_function.args]

[optimizer]
path = "torch.optim.AdamW"
[optimizer.args]
lr = 1e-3

[model]
path = "audiozen.models.spiking_fullsubnet.modeling_spiking_fullsubnet.SpikingFullSubNet"
[model.args]
n_fft = 512
hop_length = 128
win_length = 512
fdrc = 0.5
fb_input_size = 64
fb_hidden_size = 320
fb_num_layers = 2
fb_proj_size = 64
fb_output_activate_function = false
sb_hidden_size = 224
sb_num_layers = 2
freq_cutoffs = [0, 32, 128, 256]
df_orders = [5, 3, 1]
center_freq_sizes = [4, 32, 64]
neighbor_freq_sizes = [15, 15, 15]
use_pre_layer_norm_fb = true
use_pre_layer_norm_sb = true
bn = true
shared_weights = true
sequence_model = "GSN"
num_spks = 1

[acoustics]
n_fft = 512
hop_length = 128
win_length = 512
sr = 16000

[train_dataset]
path = "dataloader.SimTrainDataset"
[train_dataset.args]
rvb_scp_fpath = "/home/xhao/proj/spiking-fullsubnet/recipes/reverb/data/tr_simu_1ch.scp"
dry_scp_fpath = "/home/xhao/proj/spiking-fullsubnet/recipes/reverb/data/tr_cln.scp"
duration_in_seconds = 4.0
sr = 16000
[train_dataset.dataloader]
batch_size = 32
num_workers = 8
drop_last = true
pin_memory = true

[validate_dataset]
path = "dataloader.SimDTDataset"
[validate_dataset.args]
rvb_scp_fpath = "/home/xhao/proj/spiking-fullsubnet/recipes/reverb/data/et_simu_1ch.scp"
dry_scp_fpath = "/home/xhao/proj/spiking-fullsubnet/recipes/reverb/data/et_cln.scp"
sr = 16000
limit = 100
offset = 0
[validate_dataset.dataloader]
batch_size = 1
num_workers = 0

[[test_dataset]]
path = "dataloader.EvaluationSimDataset"
[test_dataset.args]
scp_fpath = "/home/xhao/proj/spiking-fullsubnet/recipes/reverb/data/et_simu_1ch.scp"
[test_dataset.dataloader]
batch_size = 1
num_workers = 1

[[test_dataset]]
path = "dataloader.EvaluationRealDataset"
[test_dataset.args]
scp_fpath = "/home/xhao/proj/spiking-fullsubnet/recipes/reverb/data/et_real_1ch.scp"
[test_dataset.dataloader]
batch_size = 1
num_workers = 1
